project: recomart
registry: data/registry.db
provider: local
offline_store:
    type: postgres
    host: localhost
    port: 5432
    database: postgres
    db_schema: recomart
    user: postgres
    password: admin
online_store:
    type: sqlite
    path: data/online_store.db